package com.feemanagement.demoFees.repository;

import com.feemanagement.demoFees.entity.Student;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Repository

public interface StudentRepository extends JpaRepository<Student,String> {


    Page<Student> findByStatus(String status, Pageable pageable);
    //filter by grade
    Page<Student> findByGradeAndStatus(String grade,String status,Pageable pageable);

    // @Query(value = "SELECT * FROM STUDENT_DETAILS WHERE STATUS = 'ACTIVE'",nativeQuery = true)
    List<Student> findByStatus(String status);
    //Customized query because instead of autogenerated id we use a different search criteria
   @Query(value="SELECT * FROM STUDENT_DETAILS WHERE STUDENT_ID = :studentId",nativeQuery = true)
   Optional<Student> findStudentDataById(@Param("studentId") String studentID);

    @Query(value="SELECT MAX(APP_NUMBER) FROM STUDENT_DETAILS",nativeQuery = true)
    Optional<Long> getLatestAppNumber();

    @Modifying
    @Query(value="DELETE FROM STUDENT_DETAILS WHERE STUDENT_ID = :studentId", nativeQuery = true)
    @Transactional
    Optional<Student> deleteByStudentId(@Param("studentId") String studentId);

}
